gr1 = [ ['CTACCA', 'ACCAAC', 'GCACAC', 'GAAGAA', 'CGTTAC', 'TCCTTG', 'AACGCA', 'ACAGGT', 'AGGTAA', 'AACAAT', 'ACTGTA', 'AGGTCG'],
        ['CATGCT', 'GGTCCA', 'TCTGGC', 'AGGATC', 'GTCTGA', 'AGGTTA', 'CAACTC', 'CCAACA', 'CTAACT', 'ATTCCT', 'CCAGCA', 'CTGCGG'],
        ['GCACAT', 'GTATAA', 'CATAGC', 'GACAGT', 'TTACGC', 'GTCATC', 'CTGTAA', 'GCCGTC', 'GTAACA', 'GAAGGA', 'GACCTA', 'GCAGCC'],
        ['TGCTCG', 'TTCGCT', 'CAGGAG', 'CCTATG', 'TTGAAT', 'CCTTCG', 'TAAGCA', 'TATCTG', 'TGTAAT', 'TCGCTA', 'TGCAAG', 'TTAATC'],
        ['AGCAAT', 'AACTTG', 'TGTCGG', 'TCGCCT', 'AAGACA', 'TCTCGG', 'AATGTT', 'ACTAAG', 'ATTATC', 'ACAGTT', 'AGCATG', 'AGGTGC'],
        ['AGTTGC', 'CACATC', 'ATTATG', 'ATAGCG', 'CAGCAA', 'ATTGTC', 'CAGCGG', 'CGCCTT', 'CTATGC', 'CAATAG', 'CGCTAT', 'CTGTGG'],
        ['CCAGTT', 'TCGGAA', 'CCTACC', 'GTCGCC', 'TCCAGC', 'GAACCT', 'GACCAG', 'GCCTAG', 'GTCCAC', 'GACCGT', 'GATATC', 'GCCGCA'],
        ['TTGAGC', 'AAGGAT', 'TACTTA', 'ATTCTA', 'CCAGAG', 'TAATGA', 'TATCCA', 'TGCTGC', 'TTGTCT', 'TCTGCA', 'TGTAAC', 'TTATAT']
      ]

gr2 = [ ['CGGAAT', 'AAGGCT', 'GACTGA', 'ATACGC', 'TGAGAC', 'TCGTAG', 'CATCAG', 'TAAGCT', 'CCGTAA', 'AAGCTT', 'AGTACT', 'GTCAAG'],
        ['TGCAGC', 'GTAGCA', 'AGCATC', 'CGACGT', 'ACGATG', 'CTGTAC', 'GTCCAA', 'TCGCGA', 'TAGGCA', 'GCTCTA', 'AGTCAG', 'TAGCGT'],
        ['CATTGA', 'GCGATA', 'TACGTA', 'TTCCGA', 'TAGACT', 'TTAGCC', 'CAGTCA', 'GCGTCA', 'CGAGAT', 'TAGCTA', 'CCTAGG', 'ACGGTC'],
        ['CTGATG', 'TAGTCG', 'CTAGTG', 'GTCTCA', 'TCACAG', 'GAGCTC', 'TGCTGA', 'AATCGG', 'TCAATG', 'TTAACG', 'ACTAGT', 'GCATTG'],
        ['AACTGG', 'GGTACC', 'ATTGGC', 'ATCCGT', 'TAACCG', 'CTTGAC', 'AGCTTA', 'TTCAGG', 'CGAATG', 'TCAGCA', 'AGTCTA', 'GGCTAA'],
        ['TCCAGT', 'GTATCG', 'CAGGTT', 'AGCTGT', 'GATCAC', 'GTAGTC', 'CGTAGA', 'CTATAG', 'ACTGGA', 'ACTCTG', 'GCGTAT', 'CTGTGA'],
        ['ATCGTC', 'GTACTA', 'GCTATG', 'CATCGT', 'ACGTAC', 'TGTACA', 'TCACGT', 'TCAAGC', 'GGTTCA', 'CGTACG', 'CTCAGA', 'CATGCA'],
        ['TAGAGC', 'GAACTG', 'ATCTCG', 'CGCAGT', 'GGACTT', 'CCAAGT', 'AGACTC', 'GAGTCT', 'TCAGTC', 'GTGCAC', 'AGCGCT', 'GATCGA']
      ]
