gr1 = [ ['CTATTCG', 'GTATGCG', 'TGTCACG', 'CCTAAGG', 'TTCAAGC', 'CGCTTGA', 'CATGAAC', 'CTTAGTG', 'TGGAGCA', 'AGTCTCC', 'GCTTCAT', 'CCTGATG'],
        ['ACTCAGG', 'ATCTGCA', 'TTCCTGA', 'GGCGATT', 'CTGTGAG', 'GATCACA', 'TACTAGC', 'GGCTAGA', 'CAATCGA', 'GACACTG', 'GGCACTT', 'CACAGAT'],
        ['ACACGTG', 'GCAGTAG', 'GGATCTA', 'GCTGAAT', 'CTAGTGC', 'GTGCTAT', 'GCAACTA', 'TTGCCAG', 'TTGCAGA', 'ATCAGGC', 'CGAGTCT', 'CTTCGAA'],
        ['TCTTCGA', 'CAGTACG', 'TACCAGT', 'GAATAGC', 'CTTGCAG', 'AGGCTAG', 'AGGCGTT', 'CGTTGAA', 'ACCGATC', 'CGGATTA', 'CAGTCAA', 'CGTCAGA'],
        ['AGCACTG', 'TGCACAA', 'GGAGACT', 'ACTGCAG', 'ATGCCAA', 'CTACGTA', 'CGCTACA', 'TCGAAGG', 'CTGATGG', 'TCTCGAA', 'TGCCTAA', 'TCGACTC'],
        ['AGTGCGT', 'CGTAACT', 'AGCTAGT', 'CTTACGG', 'CATGCTG', 'ATAGCGA', 'AAGGTAC', 'TATAGGC', 'GCTTAGA', 'ACGCTAT', 'CCTGACT', 'CCATGGT'],
        ['AACGTTC', 'AGCTCAA', 'ACTTGGC', 'CGCATAT', 'CTAAGCG', 'GTAGTCT', 'AAGCCTT', 'AACAGCT', 'TACGAGG', 'TCGATAC', 'TCTGGAG', 'TACGTAC'],
        ['ATCTGTC', 'ATAACCG', 'TAGCGCA', 'GCCTACA', 'AGCCGAT', 'CTACAAG', 'CTACAGC', 'TCACAAG', 'AACGGTG', 'TGACGGA', 'AACTCGT', 'TACCGGA']
      ]
      
gr2 = [ ['AGAGCAT', 'GGTCTTA', 'GGTTCAA', 'CTGGAAG', 'GATAGTC', 'GCATCAG', 'TACGACT', 'TATGTCC', 'GTAATCC', 'TCAGCCT', 'GGACTTC', 'CAGGAAT'],
        ['GTCATGC', 'CGGTCTA', 'CAAGGTT', 'ATAGCCT', 'GACCTGT', 'TGCTGAG', 'CGTGCAT', 'TACCGAT', 'GTCACAC', 'CACAGTA', 'GCTCATA', 'GCCATTC'],
        ['ACGCTTC', 'TGAGCAG', 'ACTGTCC', 'GTAACGT', 'CATGAGG', 'ACGTTGG', 'AATGCCG', 'GCATCCA', 'TTCAGTC', 'GTCGAGA', 'GTTCAAC', 'TGGACAC'],
        ['TCTTAGG', 'GCATGAT', 'TCTAACG', 'CACGAGT', 'CAACGGT', 'GACTGTG', 'AGCTGTT', 'CGTACTC', 'ACAATCG', 'AGATGCG', 'ACGATGC', 'GTTACCT'],
        ['TGATGAC', 'GAGCTAG', 'AGTCGAC', 'AGTACCT', 'CGATATC', 'GACGCTA', 'GCATCGT', 'AGCAGGT', 'CATGTGC', 'GCATACT', 'TGAGACC', 'CTTGTAC'],
        ['GTAAGTC', 'CATTGTC', 'AACATCG', 'CTGTATG', 'GAGATCG', 'TCGTGAG', 'CATGGAT', 'CATTGGA', 'ATGACGT', 'TAGACCA', 'GGTCCAT', 'ATAGGTC'],
        ['ATCTACG', 'GTTAGGC', 'CCATTGC', 'CTCATGA', 'GCTGACA', 'ACGGATA', 'ATTCCGT', 'GCATGGA', 'GGAACCT', 'TAGGCAT', 'GGTGATC', 'ATGGCTC'],
        ['GTACGGT', 'CTTAAGC', 'TGCTACT', 'AGATCAC', 'TTGGTCA', 'CAGCGTA', 'CATACAG', 'CGAAGGT', 'ACAGGTA', 'GTTGACT', 'CAATGCG', 'CAACATG']
      ]

gr3 = [ ['TGATCCG', 'TGACGTC', 'ATGCTAC', 'AGGTTCG', 'GCTACGT', 'CGGATGT', 'CGATGAT', 'AGCTGGA', 'GTTGCTA', 'CGAGATT', 'CGTCCAA', 'GAGCTTC'],
        ['TACTCGA', 'GCTACCA', 'GGTATCA', 'GAACCTC', 'TCACTGA', 'CTTCAGT', 'AATCACG', 'GCTTAAG', 'AAGTGCA', 'CGTTACG', 'TGAATCC', 'GATCGCT'],
        ['TTAGCGT', 'GGACGAT', 'GCTACTC', 'AGTGTAC', 'CGCAATC', 'TCTCATG', 'TACTGAC', 'GCCGTAA', 'GCGACAT', 'CGACGTT', 'GGCATAC', 'TGTCTCA'],
        ['AACCTTG', 'GACATCC', 'AGGACAT', 'CTCGATC', 'TTGCACC', 'TTGCCTA', 'ACAGCTC', 'ATCCAGG', 'GTCGTCA', 'ACATGCT', 'AAGGCTA', 'CCATGAC'],
        ['CACGTCA', 'CTAGCTC', 'CTATCGT', 'GCTTGTA', 'TCTACAG', 'TATCCGC', 'TGCACGT', 'ACACTGG', 'ACATCCG', 'GCAATTG', 'TATCGCG', 'CATCTGG'],
        ['CCGCATT', 'GATGTAC', 'TGCACTC', 'ATCGTGA', 'GACCTAA', 'TAACAGC', 'GCCATAG', 'GTTGCAC', 'GGTCTAG', 'ACGTGGT', 'CGAACTT', 'TACGGTC'],
        ['TGTGACT', 'TCGCCAA', 'GATGCTC', 'CGTATGA', 'CAGCACT', 'CCGAAGT', 'CGCATTG', 'TCAGTGG', 'TAATGCC', 'CAGTTCA', 'CTAGACG', 'CGAGTAG'],
        ['CGTACGT', 'ACTCGGT', 'GACGTAG', 'GTGTCTA', 'ATGAGCG', 'CGAGTGA', 'GAGACTA', 'GGTATGC', 'CAACTGA', 'TTCATGG', 'TCCGCAT', 'GACACCT']
      ]

gr4 = [ ['GAGTTCT', 'AGTTCGC', 'AGGTCTG', 'ATTCCAG', 'CCGTGTA', 'ATCGCCA', 'ATGCGCA', 'GTTCATG', 'TCTAGTC', 'ACGGTAG', 'CAAGTTG', 'TAGCCGA'],
        ['TTCAGGA', 'TACCATG', 'CGAATTC', 'ACGTCAA', 'CTGTCCA', 'ACTCTTG', 'CTACGAT', 'CAGCGAT', 'GCGTTAG', 'TGCCAGA', 'ATCACGG', 'TGGCTAT'],
        ['GACGTCT', 'GTTCGGA', 'TAGCGTG', 'CTGATCA', 'TCACAGT', 'ATTGACG', 'ATGTCGC', 'ACTACTG', 'TAGAGCC', 'TCCATGC', 'AAGACTC', 'TTACTGC'],
        ['TCACTTG', 'TGGTACC', 'ATGTGCC', 'CTGTGGA', 'TCAACGT', 'AGCCTTC', 'GTAACTG', 'TGGATGC', 'TGCGTAT', 'CACCTAG', 'CGGTATT', 'GGACATT'],
        ['AGATACC', 'CTGTCAT', 'AGTGAGC', 'TAAGGCT', 'CAGTTGT', 'GAATCTG', 'AGTCAGT', 'GAAGTCC', 'GGACTAA', 'GCTCTAA', 'CGCCATT', 'ATTCAGC'],
        ['CTTGACC', 'GAGTCTT', 'TAGGTGC', 'CTATGCC', 'GTCAGTG', 'GTCACTA', 'TAGACGC', 'GATTCAG', 'TGACATG', 'CGGTTAT', 'GTCCATA', 'ATTCGCG'],
        ['GGAATCG', 'GCTAGAA', 'AGTTGCA', 'GTTAGCG', 'CTAGAGT', 'TAGTGGC', 'ACCAGTG', 'AGGCATG', 'TTAGGCA', 'GTCCAAG', 'TCCTGTA', 'TGAAGCT'],
        ['CGTGAGT', 'CGACACT', 'GTGGTAC', 'GAGGATC', 'TGACACA', 'AGGAGTC', 'CATCCGT', 'AGATCGA', 'GAGCTGA', 'CTACCGA', 'TCGTAGC', 'CACGTAT']
      ]